project:
  type: website
  output-dir: _site

# Meta
description-meta: "Personal Website of Denis Bakin"
author-meta: "Denis Bakin"

website:
  title: "Denis Bakin"
  image: "https://quarto.org/quarto.png"
  description: "Personal Website of Denis Bakin"

  navbar:
    background: dark

    left:
#      - text: Home
#        href: index.qmd
      # - text: About
      #   menu:
      #     - text: News
      #       href: posts.qmd#category=news
      #     - text: Events
      #       href: posts.qmd#category=event
      #     - text: Contact
      #       href: contact.qmd
      # - text: Contacts
      #   href: contact.qmd
      - text: Teaching
        href: teaching.qmd

    right:
      - text: CV
        href: https://raw.githubusercontent.com/dfbakin/dfbakin/master/CV_eng.pdf
      - icon: github
        href: https://github.com/dfbakin/personal-website.git
        target: _blank

  page-navigation: true

  page-footer:
    left: "[Denis Bakin](https://github.com/dfbakin/) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: >
      Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)
      adapted by [Dr. Gang He](http://drganghe.github.io)
    right:
      - icon: github
        href: https://github.com/dfbakin/personal-website.git
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  repo-url: https://github.com/dfbakin/personal-website.git
#  repo-actions: [edit, issue, source]

  open-graph: true

  twitter-card: true
#  card-style: summary

  site-url: "https://dfbakin.com"

  # google-analytics:
  #   tracking-id: ""  # Please delete or replace with your own tracking ID
  #   anonymize-ip: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    # link-external-filter: "^(?:http:|https:)\/\/drganghe\.github\.io\/custom"
