name: Render and deploy Quarto files
on:
  push:
    branches:
      - master

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Pull website resources
        run: |
          dvc pull resources.dvc
          cd resources && wget https://raw.githubusercontent.com/dfbakin/dfbakin/master/CV_eng.pdf
          wget https://raw.githubusercontent.com/dfbakin/dfbakin/master/CV_rus.pdf

      - name: Render Quarto files
        uses: quarto-dev/quarto-actions/render@v2

      - name: Rename output directory
        run: mv _site dfbakin_com

      - name: Deploy using rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: dfbakin_com
          remote_path: /var/websites
          remote_host: dfbakin.com
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
